version: "3.5"

services:
  redis:
    image: redis
    restart: always
    ports:
    - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 60s
      timeout: 60s
      retries: 6
    ports:
      - "5672:5672"
      - "15672:15672"

#  srv:
#    build:
#      context: ./server
#    restart: on-failure
#    depends_on:
#      postgres:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#    ports:
#      - "5000:5000"
#
#  worker:
#    build:
#      context: ./bot
#    restart: on-failure
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#
#  vue:
#    build:
#      context: ./client
#    ports:
#      - "3000:3000"
volumes:
  redis:
    driver: local